CREATE TABLE IF NOT EXISTS default_songs(
   id       INTEGER  PRIMARY KEY AUTO_INCREMENT 
  ,name     VARCHAR(255) NOT NULL
  ,yt_link  VARCHAR(255) NOT NULL
  ,year     INTEGER  NOT NULL
);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('In the Mood','_CI-0E_jses',1940);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Frenesi','sMOHMYl5BCs',1940);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''ll Never Smile Again','SKyi8suBr6I',1940);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Chattanooga Choo Choo','V2aj0zhXlLA',1941);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Daddy','c8nGrDarRJQ',1941);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Stardust','CUCe-b1IQeU',1941);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('White Christmas','w9QLn7gM-hY',1942);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(I''ve Got a Gal In) Kalamazoo','WQQfK8Bqkw0',1942);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tangerine','q-JDUnZv1N0',1942);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Paper Doll','HaMeSrynug0',1943);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Pistol Packin'' Mama','Z8Jd281xrAU',1943);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('You''ll Never Know','am10msR8bEw',1943);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Swinging On a Star','rATftJiWdkw',1944);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Don''t Fence Me In','vMnLoOnrwbg',1944);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''ll be seeing you','1ld7pkvZPQk',1944);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sentimental Journey','fKCozjGub_M',1945);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Rum & Coca-Cola','WiayZdPESno',1945);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Till The End of Time','xSJ-oT2ZBa0',1945);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Prisoner of Love','lbNPg_Rp0ws',1946);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Five Minutes More','GvWEigjXVsI',1946);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('To Each His Own','0G5wqiLiPHg',1946);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Near You','CbZLpAMnclQ',1947);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Chi-Baba, Chi-Baba (My Bambino Go to Sleep)','GW_yFDZk3is',1947);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Ballerina','K3veIFyNGbo',1947);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Buttons & Bows','jfW9-0EzYxA',1948);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Nature Boy','Iq0XJCJ1Srw',1948);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''m Looking Over a Four Leaf Clover','VY-_8XOrvTs',1948);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Riders in the Sky','ais2uSUwIuY',1949);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Rudolph, the Red-Nosed Reindeer','44bL90HP0Ys',1949);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mule Train','oZ62MOvS2hQ',1949);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mona Lisa','NIDX18Xl16s',1950);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Third Man Theme','2oEsWi88Qv0',1950);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tennessee Waltz','-XCvfy6Huyc',1950);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Too Young','KaFtsqU2V6U',1951);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Cry','Iob-_shdLQ0',1951);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Unforgettable','vDN5rG3wLa4',1951);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('You Belong to Me','zQfF84ackMM',1952);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Here in My Heart','cMD-k0C1AM8',1952);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Auf Wiederseh''n Sweetheart','8WsuLH4sulA',1952);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Vaya Con Dios (may God Be With You)','QqZ0Sdz_V40',1953);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('The Song From Moulin Rouge (Where Is Your Heart)','LPDF2ORPOFQ',1953);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('How Much is That Doggy in the Window?','2AkLE4X-bbU',1953);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mister Sandman','CX45pYvxDiA',1954);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sh-Boom (Life Could Be a Dream)','Q9G0-4TWwew',1954);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Secret Love','aiueIiFJdN8',1954);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Only You (And You Alone) by The Platters','3FygIKsnkCw',1955);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sixteen Tons','Joo90ZWrUkU',1955);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Cherry Pink & Apple Blossom White','bdbAYcKfPxY',1955);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Que sera sera (Whatever will be will be)','SdhAfMor9BM',1956);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Blueberry Hill','bQQCPrwKzdo',1956);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Heartbreak Hotel','e9BLw4W5KU8',1956);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Jailhouse Rock','gj0Rz-uP4Mk',1957);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Great Balls of Fire','ZD8YPY8RBQc',1957);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('That''ll Be the Day','eq9FCBatl3A',1957);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tom Dooley','VhXuO4Gz3Wo',1958);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Volare','t4IjJav7xbg',1958);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('When','G55yNWCnXTI',1958);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mack the Knife','h8iPUK0AGRo',1959);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Smoke Gets in Your Eyes','H2di83WAOhU',1959);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(Now & then There''s) A Fool Such As I','-unOfZiTM_0',1959);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Are You Lonesome Tonight?','_cS5aCozhcA',1960);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('It''s Now Or Never','QkMVscR5YOo',1960);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Marina','sIYjIw6VmvE',1960);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Let''s Twist Again','eh8eb_ACLl8',1961);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Stand By Me','hwZNL7QVJjE',1961);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Surrender','bGYjWfp3aQI',1961);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Speedy Gonzales','v4s2AMKPHnE',1962);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Can''t Stop Loving You','r_7iRVtxui8',1962);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Telstar','ryrEPzsx1gQ',1962);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(You''re The) Devil in Disguise','emjLXdsj6xA',1963);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('If I Had a Hammer','hms_GdvOKZY',1963);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Hey Paula','W7vcRyBAQZA',1963);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Oh, Pretty Woman','Ikweq0THs88',1964);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Want to Hold Your Hand','jenWdylTtzs',1964);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('She Loves You','nGbWU8S3vzs',1964);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(I Can''t Get No) Satisfaction','nrIPxlFzDi0',1965);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Help!','2Q_ZzBGPdqE',1965);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Unchained Melody','qiiyq2xrSI0',1965);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Strangers in the Night','nHuko5BCFzA',1966);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('These Boots Are Made For Walking','SbyAZQ45uww',1966);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Good Vibrations','Eab_beh07HU',1966);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('A Whiter Shade of Pale','Mb3iPP-tHdA',1967);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('All You Need is Love','dsxtImDVMig',1967);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''m a Believer','4PQAqprjOuA',1967);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Hey Jude','A_MjCqQoLLA',1968);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Those Were the Days','QptZ8tYZAkE',1968);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Jumpin'' Jack Flash','0cPXwc-5Kw8',1968);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Get Back','IKJqecxswCA',1969);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sugar Sugar','h9nE2spOw_o',1969);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('In the Year 2525 (Exordium & Terminus)','yesyhQkYrQM',1969);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Let It Be','QDYfEBY9NM4',1970);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('In the Summertime','wvUQcnfwUUM',1970);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Venus','aPEhQugz-Ew',1970);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('My Sweet Lord','0kNGnIKUdMI',1971);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Maggie May by Rod Stewart','EOl7dh7a-6g',1971);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Brown Sugar by The Rolling Stones','59K2kF6o9Tk',1971);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('American Pie','uAsV5-Hv-7U',1972);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Popcorn','YK3ZP6frAMc',1972);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Without You','G-ZDKirjQgM',1972);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Angie','RcZn2-bGXqQ',1973);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tie a Yellow Ribbon ''round the Old Oak Tree','_dggAQk5peA',1973);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Crocodile Rock','QS-YZlJLCbM',1973);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Kung Fu Fighting','bmfudW7rbG0',1974);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Seasons in the Sun','-tPcc1ftj8E',1974);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Waterloo','Sj_9CiNkkn4',1974);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Can Help','tBBw1MEOMWI',1975);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('SOS','cvChjHcABPA',1975);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''m Not in Love','2rgepWg4rzw',1975);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Dancing Queen','xFrGuyw1V8s',1976);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Bohemian Rhapsody','fJ9rUzIMcZQ',1976);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('If You Leave Me Now','cYTmfieE8jI',1976);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Ma Baker by Boney M','oR6eKmqSEa0',1977);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Feel Love','Nm-ISatLDG0',1977);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mull of Kintyre','K5626WzsfMw',1977);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Stayin'' Alive','I_izvAbhExY',1978);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('You''re the One That I Want','itRFjzQICJU',1978);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('YMCA','CS9OO0S5w2k',1978);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Heart of Glass','WGU_4-5RaxU',1979);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Will Survive','Tth-8wA3PdY',1979);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tragedy by Bee Gees','MSVTOMkJdqs',1979);
