USE Heartbeats_dev;

INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('In the Mood','_CI-0E_jses','03:36',1940);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Frenesi','sMOHMYl5BCs','03:04',1940);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''ll Never Smile Again','SKyi8suBr6I','03:10',1940);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Chattanooga Choo Choo','V2aj0zhXlLA','08:01',1941);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Daddy','c8nGrDarRJQ','02:58',1941);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Stardust','CUCe-b1IQeU','03:39',1941);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('White Christmas','w9QLn7gM-hY','03:01',1942);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(I''ve Got a Gal In) Kalamazoo','WQQfK8Bqkw0','07:42',1942);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tangerine','q-JDUnZv1N0','03:11',1942);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Paper Doll','HaMeSrynug0','02:53',1943);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Pistol Packin'' Mama','Z8Jd281xrAU','02:49',1943);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('You''ll Never Know','am10msR8bEw','02:47',1943);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Swinging On a Star','rATftJiWdkw','02:30',1944);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Don''t Fence Me In','vMnLoOnrwbg','03:06',1944);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''ll be seeing you','1ld7pkvZPQk','03:12',1944);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sentimental Journey','fKCozjGub_M','03:10',1945);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Rum & Coca-Cola','WiayZdPESno','03:15',1945);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Till The End of Time','xSJ-oT2ZBa0','03:29',1945);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Prisoner of Love','lbNPg_Rp0ws','03:21',1946);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Five Minutes More','GvWEigjXVsI','02:31',1946);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('To Each His Own','0G5wqiLiPHg','03:15',1946);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Near You','CbZLpAMnclQ','02:55',1947);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Chi-Baba, Chi-Baba (My Bambino Go to Sleep)','GW_yFDZk3is','02:59',1947);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Ballerina','K3veIFyNGbo','03:24',1947);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Buttons & Bows','jfW9-0EzYxA','02:06',1948);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Nature Boy','Iq0XJCJ1Srw','02:52',1948);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''m Looking Over a Four Leaf Clover','VY-_8XOrvTs','02:28',1948);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Riders in the Sky','ais2uSUwIuY','03:07',1949);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Rudolph, the Red-Nosed Reindeer','44bL90HP0Ys','03:09',1949);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mule Train','oZ62MOvS2hQ','02:38',1949);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mona Lisa','NIDX18Xl16s','03:30',1950);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Third Man Theme','2oEsWi88Qv0','03:59',1950);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tennessee Waltz','-XCvfy6Huyc','03:06',1950);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Too Young','KaFtsqU2V6U','03:15',1951);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Cry','Iob-_shdLQ0','03:04',1951);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Unforgettable','vDN5rG3wLa4','03:13',1951);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('You Belong to Me','zQfF84ackMM','03:19',1952);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Here in My Heart','cMD-k0C1AM8','03:07',1952);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Auf Wiederseh''n Sweetheart','8WsuLH4sulA','02:49',1952);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Vaya Con Dios (may God Be With You)','QqZ0Sdz_V40','02:50',1953);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('The Song From Moulin Rouge (Where Is Your Heart)','LPDF2ORPOFQ','03:21',1953);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('How Much is That Doggy in the Window?','2AkLE4X-bbU','02:08',1953);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mister Sandman','CX45pYvxDiA','02:24',1954);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sh-Boom (Life Could Be a Dream)','Q9G0-4TWwew','02:50',1954);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Secret Love','aiueIiFJdN8','03:37',1954);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Only You (And You Alone) by The Platters','3FygIKsnkCw','02:45',1955);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sixteen Tons','Joo90ZWrUkU','03:04',1955);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Cherry Pink & Apple Blossom White','bdbAYcKfPxY','02:28',1955);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Que sera sera (Whatever will be will be)','SdhAfMor9BM','02:09',1956);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Blueberry Hill','bQQCPrwKzdo','02:22',1956);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Heartbreak Hotel','e9BLw4W5KU8','02:09',1956);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Jailhouse Rock','gj0Rz-uP4Mk','02:44',1957);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Great Balls of Fire','ZD8YPY8RBQc','04:03',1957);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('That''ll Be the Day','eq9FCBatl3A','02:20',1957);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tom Dooley','VhXuO4Gz3Wo','03:09',1958);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Volare','t4IjJav7xbg','05:18',1958);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('When','G55yNWCnXTI','02:27',1958);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mack the Knife','h8iPUK0AGRo','03:08',1959);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Smoke Gets in Your Eyes','H2di83WAOhU','02:41',1959);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(Now & then There''s) A Fool Such As I','-unOfZiTM_0','02:41',1959);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Are You Lonesome Tonight?','_cS5aCozhcA','03:10',1960);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('It''s Now Or Never','QkMVscR5YOo','03:20',1960);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Marina','sIYjIw6VmvE','02:45',1960);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Let''s Twist Again','eh8eb_ACLl8','02:27',1961);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Stand By Me','hwZNL7QVJjE','02:58',1961);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Surrender','bGYjWfp3aQI','01:54',1961);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Speedy Gonzales','v4s2AMKPHnE','02:38',1962);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Can''t Stop Loving You','r_7iRVtxui8','04:12',1962);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Telstar','ryrEPzsx1gQ','03:18',1962);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(You''re The) Devil in Disguise','emjLXdsj6xA','02:21',1963);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('If I Had a Hammer','hms_GdvOKZY','03:04',1963);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Hey Paula','W7vcRyBAQZA','02:25',1963);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Oh, Pretty Woman','Ikweq0THs88','03:01',1964);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Want to Hold Your Hand','jenWdylTtzs','02:37',1964);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('She Loves You','nGbWU8S3vzs','02:22',1964);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('(I Can''t Get No) Satisfaction','nrIPxlFzDi0','03:55',1965);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Help!','2Q_ZzBGPdqE','02:19',1965);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Unchained Melody','qiiyq2xrSI0','03:38',1965);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Strangers in the Night','nHuko5BCFzA','02:37',1966);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('These Boots Are Made For Walking','SbyAZQ45uww','02:29',1966);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Good Vibrations','Eab_beh07HU','03:37',1966);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('A Whiter Shade of Pale','Mb3iPP-tHdA','04:01',1967);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('All You Need is Love','dsxtImDVMig','03:52',1967);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''m a Believer','4PQAqprjOuA','02:45',1967);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Hey Jude','A_MjCqQoLLA','08:10',1968);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Those Were the Days','QptZ8tYZAkE','05:19',1968);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Jumpin'' Jack Flash','0cPXwc-5Kw8','03:37',1968);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Get Back','IKJqecxswCA','03:09',1969);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Sugar Sugar','h9nE2spOw_o','03:02',1969);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('In the Year 2525 (Exordium & Terminus)','yesyhQkYrQM','03:21',1969);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Let It Be','QDYfEBY9NM4','04:04',1970);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('In the Summertime','wvUQcnfwUUM','03:35',1970);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Venus','aPEhQugz-Ew','03:01',1970);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('My Sweet Lord','0kNGnIKUdMI','04:40',1971);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Maggie May by Rod Stewart','EOl7dh7a-6g','05:51',1971);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Brown Sugar by The Rolling Stones','59K2kF6o9Tk','03:51',1971);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('American Pie','uAsV5-Hv-7U','08:42',1972);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Popcorn','YK3ZP6frAMc','02:34',1972);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Without You','G-ZDKirjQgM','03:29',1972);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Angie','RcZn2-bGXqQ','04:40',1973);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tie a Yellow Ribbon ''round the Old Oak Tree','_dggAQk5peA','03:21',1973);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Crocodile Rock','QS-YZlJLCbM','03:54',1973);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Kung Fu Fighting','bmfudW7rbG0','03:11',1974);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Seasons in the Sun','-tPcc1ftj8E','03:27',1974);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Waterloo','Sj_9CiNkkn4','02:47',1974);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Can Help','tBBw1MEOMWI','03:58',1975);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('SOS','cvChjHcABPA','03:19',1975);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I''m Not in Love','2rgepWg4rzw','06:03',1975);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Dancing Queen','xFrGuyw1V8s','03:52',1976);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Bohemian Rhapsody','fJ9rUzIMcZQ','06:00',1976);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('If You Leave Me Now','cYTmfieE8jI','04:00',1976);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Ma Baker by Boney M','oR6eKmqSEa0','04:06',1977);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Feel Love','Nm-ISatLDG0','05:53',1977);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Mull of Kintyre','K5626WzsfMw','04:40',1977);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Stayin'' Alive','I_izvAbhExY','04:10',1978);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('You''re the One That I Want','itRFjzQICJU','03:16',1978);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('YMCA','CS9OO0S5w2k','04:02',1978);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Heart of Glass','WGU_4-5RaxU','03:44',1979);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('I Will Survive','Tth-8wA3PdY','04:58',1979);
INSERT INTO default_songs(name,yt_link,duration,year) VALUES ('Tragedy by Bee Gees','MSVTOMkJdqs','05:32',1979);